spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jbank_db
    username: jbank_user
    password: jbank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    create-schemas: true
    schemas: account
    locations: classpath:db/migration
    validate-on-migrate: true

