version: '3.8'

services:
  consul:
    image: consul:1.15.2
    container_name: jbank-consul
    restart: unless-stopped
    command: agent -server -bootstrap-expect=1 -ui -node=consul-server -client=0.0.0.0 -data-dir=/consul/data
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - consul_data:/consul/data
      - ./consul-config:/consul/config
    networks:
      - jbank-network
    healthcheck:
      test: [ "CMD", "consul", "info" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:16-alpine
    container_name: jbank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jbank_db
      POSTGRES_USER: jbank_user
      POSTGRES_PASSWORD: jbank_password
    ports:
      - "5432:5432"
    volumes:
      - jbank_postgres_data:/var/lib/postgresql/data
    networks:
      - jbank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jbank_user -d jbank_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: jbank-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - jbank_keycloak_data:/opt/keycloak/data
    networks:
      - jbank-network
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  jbank_postgres_data:
    driver: local
  consul_data:
    driver: local
  jbank_keycloak_data:
    driver: local

networks:
  jbank-network:
    driver: bridge
