server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,consul,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.umd.jbank.gateway: INFO
