CREATE TABLE account.accounts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    firstname VARCHAR(255)                            NOT NULL,
    lastname  VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    birthdate date                                    NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE account.bank_accounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency   VARCHAR(3)                              NOT NULL,
    amount     DECIMAL                                 NOT NULL,
    account_id BIGINT,
    CONSTRAINT pk_bank_accounts PRIMARY KEY (id)
);

ALTER TABLE account.accounts
    ADD CONSTRAINT uc_accounts_login UNIQUE (login);

ALTER TABLE account.bank_accounts
    ADD CONSTRAINT FK_BANK_ACCOUNTS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account.accounts (id);