server:
  port: 9083

jbank:
  keycloak:
    server-url: http://jbank-keycloak:8080
    realm: jbank
    client:
      client-id: front-ui-service
      client-secret: jbank-front-ui-secret
      registration-id: service-account
      principal-name: front-ui-service
    enable-feign-interceptor: true
    resource-server:
      enabled: true
      public-paths:
        - "/actuator/**"
        - "/api/v1/health/**"
