server:
  port: 9085

exchange:
  generator:
    enabled: true
    interval-ms: 1000
    currencies:
      - USD
      - EUR
      - CNY
      - RUB
    initial-rates:
      USD: 75.50
      EUR: 85.20
      CNY: 10.80
      RUB: 1

jbank:
  keycloak:
    server-url: http://keycloak:8080
    realm: jbank
    client:
      client-id: front-ui-service
      client-secret: jbank-front-ui-secret
      registration-id: service-account
      principal-name: front-ui-service
    enable-feign-interceptor: true
    resource-server:
      enabled: false

