server:
  port: 9084

jbank:
  keycloak:
    server-url: http://localhost:8080
    realm: jbank
    resource-server:
      enabled: true
      public-paths:
        - "/actuator/**"
        - "/api/v1/health/**"
    enable-feign-interceptor: false
