spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-route
          uri: lb://account-service
          predicates:
            - Path=/account/**, /bank-account/**
          filters:
            - name: RequestLogging
            - name: ResponseLogging
        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/cash/**
          filters:
            - name: RequestLogging
        - id: exchange-route
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
          filters:
            - name: RequestLogging
        - id: blocker-route
          uri: lb://blocker-service
          predicates:
            - Path=/validate/**
          filters:
            - name: RequestLogging
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notify/**
          filters:
            - name: RequestLogging
        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**
          filters:
            - name: RequestLogging
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
