server:
  port: 8090

jbank:
  keycloak:
    server-url: http://localhost:8080
    realm: jbank
    client:
      client-id: front-ui-service
      client-secret: jbank-front-ui-secret
      registration-id: service-account
      principal-name: front-ui-service
    enable-feign-interceptor: true
    resource-server:
      enabled: true
      public-paths:
        - "/actuator/**"
        - "/api/v1/health/**"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-route
          uri: lb://account-service
          predicates:
            - Path=/account/**, /bank-account/**
        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/cash/**
        - id: exchange-route
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
        - id: blocker-route
          uri: lb://blocker-service
          predicates:
            - Path=/validate/**
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notify/**
        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.consul: INFO